/*
equence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 +
4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
  3: 1,3
   6: 1,2,3,6
   10: 1,2,5,10
   15: 1,3,5,15
   21: 1,3,7,21
   28: 1,2,4,7,14,28
   We can see that 28 is the first triangle number to have over five divisors.

   What is the value of the first triangle number to have over five hundred divisors?
*/

#include<stdlib.h>
#include<stdio.h>
#include <stdbool.h>
#include <math.h>

int main(int argc, char *argv[]){
    
    int limit;//the number of divisors is the limit
    long triangle = 0;//incrementing the triangle numbers
    int count = 0;//the counter up to the limit
    bool found = false;

    if(sscanf(argv[1], "%i", &limit)!=1){
        printf("error");
    }
    
    for(long n = 1; n > 0; n++){
        count = 0;
        triangle+=n;//add the new number to get next triangle number
        //we try each divisor up to n
        for (long i = 1;i < sqrt(triangle); i++){
            //uneven numbers on average have fewer divisors
            if(triangle%2 != 0){
                break;
            }
            if(triangle%i==0){
                count+=2;
                if(count>limit){
                    found = true;
                    printf("result: %lu", triangle);
                    break;
                }
            }
        }
        if(found==true){
              break;
        }
    }
    return 0;
}
